import type { ViewerConfig, UIState } from '@/types';

export const DEFAULT_CONFIG: ViewerConfig = {
  aperture: 0.15,
  backgroundDashSize: 8,
  backgroundFillColor: '#000000',
  backgroundFillOpacity: 0,
  backgroundSimplification: 3,
  backgroundStrokeColor: '#000000',
  backgroundStrokeOpacity: 1,
  backgroundStrokeWidth: 0.12,
  backgroundThreshold: 140,
  backgroundUseDashArray: false,
  backgroundWiggle: false,
  blurMode: 'gaussian',
  cameraZoom: 1,
  enableBackground: true,
  enableOutlinePaths: true,
  facingMode: 'user',
  highThreshold: 0.02,
  lowThreshold: 0.02,
  motionBlurAmount: 60,
  motionBlurAngle: 0,
  outlinePathMinPathLength: 5,
  outlinePathSimplification: 4,
  outlinePathsDashSize: 8,
  outlinePathsFillColor: '#000000',
  outlinePathsFillOpacity: 0,
  outlinePathsStrokeColor: '#000000',
  outlinePathsStrokeOpacity: 0.6,
  outlinePathsStrokeWidth: 0.3,
  outlinePathsUseDashArray: false,
  outlinePathsWiggle: false,
  useBackgroundFill: false,
  useBezierBackground: true,
  useBezierOutlinePaths: true,
  useOutlinePathsFill: false,
};

export const DEFAULT_UI_STATE: UIState = {
  expandBackgroundStyling: true,
  expandCameraSettings: true,
  expandEdgeDetection: true,
  expandOutlinePathStyling: true,
  layerOrder: ['background', 'outlinePaths'],
  showLeftPanel: true,
  showRightPanel: true,
};
